Feat/105
marcosdosea/GestaoAnimal pull request #106
Opened 2021-02-11 14:52 UTC by valeriabarbosasi

Melhorias nos casos de uso Manter Animal e Manter Consulta

2021-02-11 14:54 UTC, Eldeerick requested changes
Por favor descreva no título do pull request uma frase com o resumo das mudanças.

2021-02-14 00:16 UTC, Eldeerick commented
A lista de organização ao criar ou editar um animal não está funcionando.

2021-02-14 01:18 UTC, valeriabarbosasi commented
> 
> 
> A lista de organização ao criar ou editar um animal não está funcionando.

Eu ainda não havia implementado o caso de uso organização nessa branch (PR)

2021-02-17 19:31 UTC, Eldeerick commented
Considerando que todas as mudanças desse pull request estão implementadas em #108 este pull request será fechado. Close #106

2021-02-17 19:32 UTC, closed without merging