Implementação do caso de uso Manter Organizacao
marcosdosea/GestaoAnimal pull request #108
Opened 2021-02-11 21:41 UTC by valeriabarbosasi

Exibição do nome da organização no index, edit, delete,criate,details do Caso de uso Manter animal
#107

2021-02-16 22:16 UTC, Eldeerick requested changes

2021-02-16 22:16 UTC, Eldeerick commented on Codigo/GestaoAnimalWeb/Controllers/AnimalController.cs
> +            IEnumerable<Pessoa> listaPessoas = _pessoaService.ObterTodos();
Variável duplicada na função de Create, gerando erro.

2021-02-17 19:29 UTC, Eldeerick approved these changes

2021-02-18 22:38 UTC, GCaio7 approved these changes

2021-02-18 23:07 UTC, merged