#83 implementação de PessoaService, PessoController, PessoaModel e da…
marcosdosea/GestaoAnimal pull request #84
Opened 2021-02-01 02:57 UTC by Thiago473

Implementação de caso de uso Manter Pessoa

2021-02-01 03:44 UTC, Eldeerick requested changes
O código não está funcionando. Existem diversos erros que precisam ser corrigidos.
- Está faltando adicionar o transiente de IPessoaService e PessoaService em Startup.cs
- A classe PessoaService não está pública, então ela não pode ser vista por outros arquivos que tentam utilizá-la.
- Está faltando o mapper PessoaProfile na pasta Mappers, sem ele não é possível realizar o mapeamento entre PessoaModel e Pessoa.
- Está faltando o Construtor de PessoaController, sem o construtor não é possível acessar a classe de serviço PessoaService. 
  - Foi criada uma variável listaPessoasModel para ser enviada para a view em Index() porém o que está sendo enviado é listaPessoas.

Erros como esses sugerem que o código não foi nem sequer testado, pois é impossível de rodá-lo sem corrigir os problemas citados.

2021-02-01 03:49 UTC, Eldeerick commented
Quantos as Views, é importante remover o IdPessoa do cadastro e da edição da Pessoa, visto que esse código está com autoincrement no banco. É importante também traduzir as mensagens das views, é bom ver como ficaram nos outros casos de uso para manter o padrão.  
No Index mantenha somente alguns dos atributos da pessoa visíveis, não é necessários listar todos eles ali.

2021-02-02 02:00 UTC, Eldeerick requested changes
Falta ainda o PessoaProfile dentro de Mapper no projeto GestaoAnimalWeb, sem ele o AutoMapper não funciona.

2021-02-02 03:16 UTC, Eldeerick commented
![image](https://user-images.githubusercontent.com/26186645/106547316-c62f1a80-64eb-11eb-9f03-e145aacc2662.png)
A view Index está com os itens completamente embaralhados

2021-02-08 22:49 UTC, Eldeerick approved these changes

2021-02-08 23:26 UTC, GCaio7 approved these changes

2021-02-09 00:12 UTC, merged

2021-02-09 00:12 UTC, valeriabarbosasi commented
Show de bola, parabéns!